#!/usr/bin/python3
def raise_exception():
    return 1337 + "foo"
